timeout = 1000
max = 100
width = 40
height = 600
border_offset = 3
bar_padding = 3

# Keep on the right side
anchor = top right
orientation = vertical
margin = 0 100 0 0 

# Brightness slider orange (e.g., #ff9f43 with opacity -> ff9f4399)
bar_color = ff9f4399
