timeout = 1000
max = 100
width = 60
height = 600
border_offset = 5
bar_padding = 5

# Move to the left side
anchor = top left
orientation = vertical
margin = 11 0 0 111 

# Volume slider blue (e.g., #3b6feb with opacity -> 3b6feb99)
bar_color = 3b6feb99

[style.muted]
background_color = 032cfc
