timeout = 1000
max = 100
bar_color = FFFFFF

# [output.left]
# name = DP-1

# [output.ips]
# match = DELL U2722DE
width = 60
height = 600
border_offset = 5
bar_padding = 5
anchor = top right
orientation = vertical
margin = 11 111 0 0
timeout = 3000

bar_color = 99333399

[style.muted]
background_color = 032cfc
